### ISSUE TITLE
Correct services starting order

### ISSUE THREAD

**Issue by compgeniuses** [elestio-examples/erpnext#2]
I am trying to have the services managed by systemd, and iw as wondering if you could assist me with the correct service starting order

for these services

redis-queue.service
db.service
backend.service
configurator.service
create-site.service
frontend.service 
queue-long.service
queue-short.service
scheduler.service
websocket.service

**Comment by jbenguira** [comment]
Hey @compgeniuses 
Since this repo is all about docker version I would say it's off topic.
I would recommend to ask instead in the official repo here:
https://github.com/frappe/erpnext/issues
